### ISSUE TITLE
Rework website colors

### ISSUE THREAD

**Issue by ctmbl** [iScsc/blog.iscsc.fr#80]
## Context
The website supports two themes:
- light
- dark

therefore every content should support both.

## Problem
However currently sometimes hardcoded colored are used sometimes its configurable ones (see [CSS file](https://github.com/lukeorth/poison/blob/master/layouts/partials/head/css.html) and the [config file](https://github.com/iScsc/blog.iscsc.fr/blob/main/src/config.toml)).
Also sometimes a color is used in a non-intended way, for example a background color is used as a font-color, which could result in invisible words for some config.

## Tasks
- [ ] list hardcoded color 
- [ ] change hardcoded colors to configurable
- [ ] check that every light color has its dark counter-part and vice versa
- [ ] list color usage and verify that an appropriate color is used
- [ ] test in light mode
- [ ] test in dark mode
